name: docs_pages_workflow

# Based upon [Michael Altfield's](https://stackoverflow.com/users/1174102/michael-altfield)
# stackoverflow [answer](https://stackoverflow.com/a/62967771/2846766)
# to a question asking how to do this.

# Execute this workflow automatically when we push to main
on:
  push:
    branches: [ main ]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:

    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update && apt-get install -y git
        git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash

    - name: Execute script to build documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/build_docs.sh"
      shell: bash
